# Accessing/Changing specific elements, rows, columns, etc.

## Basics of indexing

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
a.shape

(2, 7)

In [7]:
#Getting a specific element, [row , column]
# Get 6

a[0,5]

6

In [8]:
#Get 10

a[1,2]

10

In [10]:
#Getting a specific row (use slicing)
#Get the first row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
# Getting a specific column
#Get the sixth column

a[:,5]

array([ 6, 13])

In [12]:
# or... use negative indexing
a[: , -2]

array([ 6, 13])

In [13]:
#Getting a little more fancy [startindex:stopindex:stepsize]
#Accessing elements between 2 and 6 with a stepsize of 2

a[0, 1:6:2]

array([2, 4, 6])

In [14]:
# Or.... negative indexing

a[0, 1:-1:2]

array([2, 4, 6])

In [16]:
#Changing an element eg changing the 10
a[1,2] = 17
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 17 11 12 13 14]]


In [17]:
# Changing for a series of numbers eg for an entire column
# Change both rows in the fourth column

a[:,3] = 20
print(a)

[[ 1  2  3 20  5  6  7]
 [ 8  9 17 20 12 13 14]]


In [19]:
#We can also assign different values to both rows eg

a[:,3] = (30,40)
print(a)

[[ 1  2  3 30  5  6  7]
 [ 8  9 17 40 12 13 14]]


## *3d example

In [20]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
#Get specific element(work outside in)
#In the very first row, get the second element in the second row which is 4

b[0,1,1]

4

In [22]:
# Get the second rows in the twon parts

b[:,1,:]

array([[3, 4],
       [7, 8]])

In [23]:
#Get the first rows in the two parts

b[:,0,:]

array([[1, 2],
       [5, 6]])

In [26]:
#change the elements in the last part

b[1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [3 4]]

 [[9 9]
  [8 8]]]
